### ISSUE TITLE
android.os.NetworkOnMainThreadException

### ISSUE THREAD

**Issue by alromh87** [nativescript-community/https#25]
Using this module on NS view-model i get NetworkOnMainThreadException, Im confused since documentation states:

- Everything runs on a native background thread

Im using:
https.enableSSLPinning({ host: '192.168.1.15', certificate, allowInvalidCertificates: false, validatesDomainName: false })

**Comment by skhye05** [comment]
I am getting the same error. any Help?

**Comment by dvdbrk** [comment]
+1

**Comment by TinusJ** [comment]
+1

**Comment by AresDev** [comment]
+1

**Comment by danielGz** [comment]
+1

**Comment by roblav96** [comment]
@alromh87 
```typescript
import * as application from 'tns-core-modules/application'
application.android.on('activityCreated', function activityCreated(args) {
	android.os.StrictMode.setThreadPolicy(new android.os.StrictMode.ThreadPolicy.Builder().permitAll().build())
})
```

**Comment by tokiroto** [comment]
I wonder, whether there should be a correct implementation of the plugin. Since why this exception happens? If it really runs in the main thread, it might create a problem later. Are there any updates on it?

Update:
And yeah, it proves I was right. Now I am working with http request with heavy response, about 30-40 mb (having attachments with base64 strs) at the moment. And it freezes dead the device, and if you attempt to refresh the list it then crashes with OutOfMemory exception. Any solution yet?

**Comment by antonio92cop** [comment]
it is a bad limitation of nativescript

**Comment by a92c** [comment]
@tokiroto nativescript works only on one main thread. For longer requests there will be a freeze or crash of the device.

Any solution for this problem thanks?

**Comment by jnorkus** [comment]
This issue makes the plugin unusable.

**Comment by vallemar** [comment]
+1

**Comment by farfromrefug** [comment]
@vallemar could you explain a bit more what s  happening for you?
