### ISSUE TITLE
Cannot read https of undefined

### ISSUE THREAD

**Issue by leocrawf** [nativescript-community/https#69]
When I was uisng  version 2.1.0 I had no issues. Now with 2.2.1, I get Cannot read https of undefined.

**Comment by ghinazi** [comment]
getting the same error

**Comment by hrebeniuk** [comment]
getting the same error

**Comment by farfromrefug** [comment]
Can you share the error callstack

**Comment by aribghilas** [comment]
getting the same error

**Comment by jamescodesthings** [comment]
@farfromrefug

Stack from the same error here, android only issue for me, ios works a charm using the latest packages:
```
TypeError: Cannot read property 'https' of undefined
JS:     at getClient (file: node_modules/@nativescript-community/https/https.android.js:265:0)
JS:     at createRequest (file: node_modules/@nativescript-community/https/https.android.js:370:0)
JS:     at file: node_modules/@nativescript-community/https/https.android.js:512:0
JS:     at new ZoneAwarePromise (file: node_modules/@nativescript/zone-js/zone-nativescript.js:902:0)
JS:     at Object.request (file: node_modules/@nativescript-community/https/https.android.js:510:0)
JS:     at ApiService.request (file: src/app/shared/services/api.service.ts:110:34)
JS:     at ApiService.post (file: src/app/shared/services/api.service.ts:51:20)
JS:     at AuthService.auth (file: src/app/shared/services/auth.service.ts:212:32)
JS:     at file: src/app/shared/services/auth.service.ts:61:17
JS:     at new ZoneAwarePromise (file: node_modules/@nativescript/zone-js/zone-nativescript.js:902:0)
JS:     at AuthService.signIn (file://...
JS: Error message: Cannot read property 'https' of undefined
```

looks like it's this line:
```
cookieJar = new com.nativescript.https.QuotePreservingCookieJar(cookieManager);
```

Using `@nstudio/nativescript-https@3` as suggested by https://nativescript.org/blog/nativescript-7-compatible-plugins/
does not have this issue but has loads more for me on android.

Env for me is:
```
ns info
✔ Getting NativeScript components versions information...
✔ Component nativescript has 7.0.3 version and is up to date.
✔ Component @nativescript/core has 7.0.0 version and is up to date.
✔ Component @nativescript/ios has 7.0.0 version and is up to date.
✔ Component @nativescript/android has 7.0.0 version and is up to date.

node@latest & npm@latest on osx via nvm.
project is loosely based on  tns-template-drawer-navigation-ng

running on a Pixel 3a AVD @ api level 30 w/Play services
```

For anyone updating to nativescript@7, what I've tried:
`@nstudio/nativescript-https@3.0.0`:
 - Error unless I set `useLegacy:true`, the error is 'could not call onResponse' and it's thrown up the callstack so it causes full app crash if not discarding errors.
 - Does not seem to respect `allowLargeResponse: true`, the response/content comes back as a `null` and then throws an error when trying to do `Https.parseJson()` on it.
- Seems inconsistent, on iOS I get an object in `response.content` from a request with a JSON response, on android I can't get this consistently.

`nativescript-https@2.2.1`: This error.
`nativescript-https@2.1.0`: works.

My webpack resolve/alias are:
```
alias: {
        "utils/utils": "@nativescript/core/utils",
        "tns-core-modules/ui/core/view/view": "@nativescript/core/ui/core/view",
        "tns-core-modules/file-system/file-system": "@nativescript/core/file-system",
        '~/package.json': resolve(projectRoot, 'package.json'),
        '~': appFullPath,
        "tns-core-modules": "@nativescript/core",
        "nativescript-angular": "@nativescript/angular",
      },
```

I forget if any of those were due to nativescript-https@2.1.0 on nativescript@7 but worth mentioning in case anyone's here with similar issues to me.

**Comment by farfromrefug** [comment]
@jamescodesthings awesome that s what i need to fix this!
So what s happening is that it is not finding a native library, or more precisely not building it.
So you understand `QuotePreservingCookieJar` comes as java source with this plugin. For some reason it is not picked up by your app.
There might be multiple reasons to that:
* build error: do you see any error in your build?
* metadata error: are you doing metadata filtering ? (https://docs.nativescript.org/core-concepts/metadata)

PS: i dont know about the nstudio version. It is a direct fork of this so it dont know.
PS2: 2.1.0 is working because it was not supporting cookis and thus was not needing that native class

**Comment by jamescodesthings** [comment]
Makes sense to me, just jumping into a meeting I'll get back to your questions after =]

**Comment by jamescodesthings** [comment]
We're not doing any metadata filtering and there are no errors in the gradle build/ns build.

I'm not seeing it being built at all. 

Checked out the `node_modules` folder for the package and found no java/aar files in there. If I copy the contents of `java/com/nativescript/https` (downloaded from github) to my node_modules folder and rebuild I get a `Built aar for nativescript-https` during prepare and then things work again.

Checking out the `.npmignore`  the java files in the repo are ignored https://github.com/EddyVerbruggen/nativescript-https/blob/master/src/.npmignore

Not sure if there's meant to be an aar being packaged during the publish step to npm or if it's just meant to be the java files in the plugin?

**Comment by farfromrefug** [comment]
Awesome thanks ! and I know now why it worked here. I will release in a few hours! Sorry for the trouble
Edit: no aar packaged. Npmignore is the issue here! My fault

**Comment by farfromrefug** [comment]
@jamescodesthings should be fixed in 2.2.2!
Let me know

**Comment by aribghilas** [comment]
for me i just add the "httpbin.org.cer" (demo/app/asstets) to the Android Emulator and that's worked .
to add the file to an adroid Emulator see  https://medium.com/@noumaan/ssl-app-dev-a2923d5113c6  at  " Android Emulator"

**Comment by jamescodesthings** [comment]
Hey @farfromrefug sorry for the delay, had to refactor our use of the plugin to test. It works now at version 2.2.2. Cracking job, cheers =]
